### ISSUE TITLE
[DB] 경로 콜렉션 정의

### ISSUE THREAD

**Issue by hyex** [Team-Scookie/scookie_server#2]
# 경로 콜렉션 정의

Naming, Type, Field 에 관한 확정이 필요합니다

---

### Collection Field

```js
point_id: { type: Number, required: true, unique: true }, 
user_id: { type: Number, required: true },
latitude: { type: String, required: true },
longitude: { type: String, required: true },
createdAt: { type: Date },
updatedAt: { type: Date },
```

### Current result

![image](https://user-images.githubusercontent.com/48546343/92945373-261b1b00-f490-11ea-95f5-105f962c2fb9.png)

**Comment by 100-yeeun** [comment]
lat/long이라고 하기도하던데요! 뭐가 나을까요?
그 카멜이랑 스네이크 원래 같이 쓰기도 하는 건가요?

**Comment by hyex** [comment]
## 전체 DB 적용 사항
1. DB field명은 camelCase
2. latitude/longitude 
3. collection에 개발자가 부여하는 id 없이 가보자!
---
## point DB 적용 사항
1. user_id type: String
